// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.24.3
// source: discovery_msg.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DiscoveryMsg_Type int32

const (
	DiscoveryMsg_Announce  DiscoveryMsg_Type = 0
	DiscoveryMsg_SearchReq DiscoveryMsg_Type = 1
	DiscoveryMsg_SearchRes DiscoveryMsg_Type = 2
)

// Enum value maps for DiscoveryMsg_Type.
var (
	DiscoveryMsg_Type_name = map[int32]string{
		0: "Announce",
		1: "SearchReq",
		2: "SearchRes",
	}
	DiscoveryMsg_Type_value = map[string]int32{
		"Announce":  0,
		"SearchReq": 1,
		"SearchRes": 2,
	}
)

func (x DiscoveryMsg_Type) Enum() *DiscoveryMsg_Type {
	p := new(DiscoveryMsg_Type)
	*p = x
	return p
}

func (x DiscoveryMsg_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DiscoveryMsg_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_discovery_msg_proto_enumTypes[0].Descriptor()
}

func (DiscoveryMsg_Type) Type() protoreflect.EnumType {
	return &file_discovery_msg_proto_enumTypes[0]
}

func (x DiscoveryMsg_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DiscoveryMsg_Type.Descriptor instead.
func (DiscoveryMsg_Type) EnumDescriptor() ([]byte, []int) {
	return file_discovery_msg_proto_rawDescGZIP(), []int{0, 0}
}

type DiscoveryMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type   DiscoveryMsg_Type `protobuf:"varint,1,opt,name=type,proto3,enum=discovery.DiscoveryMsg_Type" json:"type,omitempty"`
	PInfos []*PeerInfo       `protobuf:"bytes,2,rep,name=pInfos,proto3" json:"pInfos,omitempty"`
	Size   uint32            `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *DiscoveryMsg) Reset() {
	*x = DiscoveryMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_discovery_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiscoveryMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryMsg) ProtoMessage() {}

func (x *DiscoveryMsg) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryMsg.ProtoReflect.Descriptor instead.
func (*DiscoveryMsg) Descriptor() ([]byte, []int) {
	return file_discovery_msg_proto_rawDescGZIP(), []int{0}
}

func (x *DiscoveryMsg) GetType() DiscoveryMsg_Type {
	if x != nil {
		return x.Type
	}
	return DiscoveryMsg_Announce
}

func (x *DiscoveryMsg) GetPInfos() []*PeerInfo {
	if x != nil {
		return x.PInfos
	}
	return nil
}

func (x *DiscoveryMsg) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type PeerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pid  string   `protobuf:"bytes,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Addr []string `protobuf:"bytes,2,rep,name=addr,proto3" json:"addr,omitempty"`
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_discovery_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_discovery_msg_proto_rawDescGZIP(), []int{1}
}

func (x *PeerInfo) GetPid() string {
	if x != nil {
		return x.Pid
	}
	return ""
}

func (x *PeerInfo) GetAddr() []string {
	if x != nil {
		return x.Addr
	}
	return nil
}

var File_discovery_msg_proto protoreflect.FileDescriptor

var file_discovery_msg_proto_rawDesc = []byte{
	0x0a, 0x13, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x5f, 0x6d, 0x73, 0x67, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79,
	0x22, 0xb5, 0x01, 0x0a, 0x0c, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x4d, 0x73,
	0x67, 0x12, 0x30, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x1c, 0x2e, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x2e, 0x44, 0x69, 0x73, 0x63,
	0x6f, 0x76, 0x65, 0x72, 0x79, 0x4d, 0x73, 0x67, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x2b, 0x0a, 0x06, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x2e,
	0x50, 0x65, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04,
	0x73, 0x69, 0x7a, 0x65, 0x22, 0x32, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08,
	0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x10, 0x02, 0x22, 0x30, 0x0a, 0x08, 0x50, 0x65, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x70, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x42, 0x38, 0x5a, 0x36, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x61, 0x6d, 0x62, 0x6f, 0x6c, 0x6c,
	0x77, 0x6f, 0x6e, 0x67, 0x2f, 0x72, 0x61, 0x69, 0x6e, 0x62, 0x6f, 0x77, 0x62, 0x65, 0x65, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72,
	0x79, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_discovery_msg_proto_rawDescOnce sync.Once
	file_discovery_msg_proto_rawDescData = file_discovery_msg_proto_rawDesc
)

func file_discovery_msg_proto_rawDescGZIP() []byte {
	file_discovery_msg_proto_rawDescOnce.Do(func() {
		file_discovery_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_discovery_msg_proto_rawDescData)
	})
	return file_discovery_msg_proto_rawDescData
}

var file_discovery_msg_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_discovery_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_discovery_msg_proto_goTypes = []interface{}{
	(DiscoveryMsg_Type)(0), // 0: discovery.DiscoveryMsg.Type
	(*DiscoveryMsg)(nil),   // 1: discovery.DiscoveryMsg
	(*PeerInfo)(nil),       // 2: discovery.PeerInfo
}
var file_discovery_msg_proto_depIdxs = []int32{
	0, // 0: discovery.DiscoveryMsg.type:type_name -> discovery.DiscoveryMsg.Type
	2, // 1: discovery.DiscoveryMsg.pInfos:type_name -> discovery.PeerInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_discovery_msg_proto_init() }
func file_discovery_msg_proto_init() {
	if File_discovery_msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_discovery_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiscoveryMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_discovery_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PeerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_discovery_msg_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_discovery_msg_proto_goTypes,
		DependencyIndexes: file_discovery_msg_proto_depIdxs,
		EnumInfos:         file_discovery_msg_proto_enumTypes,
		MessageInfos:      file_discovery_msg_proto_msgTypes,
	}.Build()
	File_discovery_msg_proto = out.File
	file_discovery_msg_proto_rawDesc = nil
	file_discovery_msg_proto_goTypes = nil
	file_discovery_msg_proto_depIdxs = nil
}
